config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  use_doorkeeper
  default_url_options host: 'localhost'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    confirmations: 'confirmations' }

  resource :search do
    post :result
    get :result
  end

  resources :questions do
    resources :answers do
      resources :comments
      post :position_edit, :cancel_choice
    end
    resources :comments
    post :subscribe, :cancel_subscrition
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :users, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  root to: 'questions#index'
  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, :title, presence: true

  has_many :answers, foreign_key: :reply_to_id, dependent: :destroy
  has_many :attachments, dependent: :destroy, as: :attachmentable
  has_many :comments, dependent: :destroy, as: :article

  belongs_to :user

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  after_create :update_reputation

  private

  def update_reputation
    CalculateReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

class Api::V1::QuestionsController < Api::V1::BaseController
  protect_from_forgery with: :null_session

  def create
    @question = Question.create(question_params.merge(user_id: current_resource_owner.id))
    respond_with @question
  end

  def index
    respond_with Question.all
  end

  def show
    respond_with Question.find(params[:id])
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :load_question, only: %i[show edit update destroy]
  before_action :load_question_by_question_id, only: %i[subscribe cancel_subscrition]
  before_action :build_answer, only: %i[show]
  after_action :publish_question, only: [:create]
  protect_from_forgery except: :update
  authorize_resource
  check_authorization

  def index
    respond_with(@questions = Question.all)
  end

  def show; end

  def new
    respond_with(@question = Question.new)
  end

  def edit; end

  def create
    respond_with(@question = Question.create(question_params.merge(user_id: current_user.id, subscribers: [current_user.id])))
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with @question.destroy
  end

  def subscribe
    return unless current_user

    return if @question.subscribers.include? current_user.id

    @question.subscribers += [current_user.id]
    @question.save
  end

  def cancel_subscrition
    return unless current_user

    return unless @question.subscribers.include? current_user.id

    @question.subscribers -= [current_user.id]
    @question.save
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def load_question_by_question_id
    @question = Question.find(params[:question_id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def interpolation_options
    { resource_name: 'New awesome question', time: @question.created_at, user: current_user.email }
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast 'questions',
                                 ApplicationController.render(
                                   partial: 'questions/question',
                                   locals: { question: @question, user: current_user }
                                 )
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.slim
div class= "answer_#{answer.id}"
  - if answer.persisted?
    strong style="display: inline-block;" Rate:
    p style="display: inline-block;" class="pos_answer_count" = "#{answer.pos_answers_users.length}"
    p style="display: inline-block;" ||
    p style="display: inline-block;" class="neg_answer_count" = "#{answer.neg_answers_users.length}"
    h4 Body:
    p= answer.body
    strong Files:
    ul
      -answer.attachments.each do |a|
        li= link_to a.file.identifier, a.file.url
      - if answer.attachments.empty?
        li Empty file list
    p = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
    .answer-errors
    p
      = form_for [question, answer], remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
        = f.label :body, 'Answer'
        = f.text_area :body
        = f.submit 'Save'
      = button_to 'Destroy answer', question_answer_path(question, answer), method: :delete, remote: true
    hr
    h4 Answer Comments
    .answer_comments
      div class="answer_comments_#{answer.id}"
        - if !answer.comments[0].nil?
          - answer.comments.each do |comment|
            = render 'questions/comments', comment: comment, answer: answer, question: question, user: user
        - else
          p There are no comments, be first who write smth
      = form_for [question, answer, answer.comments.build], remote: true, data: { type: :json },
              html: { class: "new_answer_comment" } do |f|
        = f.hidden_field :is_question?, value: false
        = f.label :body, "."
        = f.text_area :body
        = f.submit 'Create'

app/views/questions/_answers.html.slim
hr
h2 Answers
- question.answers.each do |answer|
  div class= "answer_#{answer.id} answer_point" data-answer-id=answer.id
    - if answer.persisted?
      -cache answer do
        strong style="display: inline-block;" Rate:
        p style="display: inline-block;" class="pos_answer_count" = "#{answer.pos_answers_users.length}"
        p style="display: inline-block;" ||
        p style="display: inline-block;" class="neg_answer_count" = "#{answer.neg_answers_users.length}"
        h4 Body:
        p class="answer_body" = answer.body
        strong Files:
        ul
          - answer.attachments.each do |a|
            li= link_to a.file.identifier, a.file.url
          - if answer.attachments.empty?
            li Empty file list
        - if user
          - unless answer.user_id.equal? user.id
            .position-answers-errors
            p = button_to 'Like', question_answer_position_edit_path(question, answer),
                  method: :post, remote: true, name: "choice", form_class: 'change_pos'
            p = button_to 'Dislike', question_answer_position_edit_path(question, answer),
                  method: :post, remote: true, name: "choice", form_class: 'change_pos'
            p = button_to 'Cancel', question_answer_cancel_choice_path(question, answer),
                  method: :post, remote: true, name: "cancel", form_class: 'cancel'
          - if answer.user_id.equal? user.id
            p = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
            .answer-errors
            - if user
              p
                = form_for [question, answer], remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
                  = f.label :body, 'Answer'
                  = f.text_area :body
                  = f.submit 'Save'
                = button_to 'Destroy answer', question_answer_path(question, answer), method: :delete, remote: true
        hr
        h4 Answer Comments
        .answer_comments
          div class="answer_comments_#{answer.id}"
            - if !answer.comments[0].nil?
              - answer.comments.each do |comment|
                = render 'questions/comments', comment: comment, answer: answer, question: question, user: user
            - else
              p There are no comments, be first who write smth
        - if user
          = form_for [question, answer, answer.comments.build],
                remote: true, data: { type: :json },
              html: { class: "new_answer_comment" } do |f|
            = f.hidden_field :is_question?, value: false
            = f.label :body, "."
            = f.text_area :body
            = f.submit 'Create'
          hr
    hr

app/views/questions/_attachment_fields.html.slim
.nested-fields
  .field
    = f.label :file
    = f.file_field :file
    = link_to_remove_association "remove file", f

app/views/questions/_comments.html.slim
-if defined? answer
  div class="comment_#{comment.id}" id=answer
    -cache comment
      p=comment.body
    -if user
      =button_to 'Destroy comment', question_answer_comment_path(question, answer, comment),
          method: :delete, remote: true, name: "answer_comment_destroy" if user.id.equal? comment.user_id
    hr
-else
  div class="comment_#{comment.id}"
    -cache comment
      p=comment.body
    -if user
      = button_to 'Destroy comment', question_comment_path(question, comment),
          method: :delete, remote: true, name: "question_comment_destroy" if user.id.equal? comment.user_id
    hr

app/views/questions/_question.html.slim
.card
  .card-body
    - if user
      - unless question.subscribers.include? user.id
        p = button_to 'Subscribe', question_subscribe_path(question),
            method: :post, remote: true
      - else
        h6 Subscribed
        p = button_to 'Cancel sub', question_cancel_subscrition_path(question),
            method: :post, remote: true, params: { question_id: question.id }
    h2 Question
    strong Title:
    p = question.title
    strong Body:
    p = question.body
    strong Files:
    ul
      - question.attachments.each do |a|
        li= link_to a.file.identifier, a.file.url
    p = link_to 'See answers', question_path(question)
    - if user
      - if question.user_id.equal? user.id
        p = link_to 'Edit', '', class: 'edit-question-link', data: { question_id: question.id, user: user }
        p
          = form_for question, remote: true, html: { id: "edit-question-#{question.id}" } do |f|
            = f.label :title
            p= f.text_field :title
            = f.label :body, 'Text'
            p= f.text_area :body
            = f.submit 'Save'
        p = button_to 'Destroy question', question_path(question), method: :delete, remote: true

    hr
    h4 Question Comments
    .comments
      - if !question.comments[0].nil?
        - question.comments.each do |comment|
          = render 'questions/comments', comment: comment, question: question, user: user
      - else
        p There are no comments, be first who write smth

app/views/questions/_questions.html.slim
- for question in questions
  .col-sm-6 style="max-width: 100%"
    = render 'question', question: question, user: current_user

app/views/questions/cancel_subscrition.js.erb
<% if @question.errors.present? %>
<% @question.errors.full_messages.each do |message| %>
$('.questions-errors').html('<%= j message %>')
<% end %>
<% else %>
console.log("SUBSCRIBE")
$('.questions').html('<%= j render 'questions/questions', questions: Question.all %>');
<% end %>

app/views/questions/destroy.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.questions-errors').html('<%= j message %>')
  <% end %>
<% else %>
  console.log("DESTROY")
  $('.questions').html('<%= j render 'questions/questions', questions: Question.all %>');
<% end %>

app/views/questions/index.html.slim
= render 'questions', questions: @questions, user: current_user

app/views/questions/new.html.slim
.col-sm-6 style="max-width: 100%"
  .card
    .card-body
    h1 New Question
    = form_for @question do |f|
      p
        = f.label :title
        = f.text_field :title
      p
        = f.label :body, 'Text'
        = f.text_area :body
      p Add Attachments:
      p
        = f.fields_for :attachments, @question.attachments.build do |a|
          = render 'attachment_fields', f: a
      p
        = link_to_add_association "add file", f, :attachments
      = f.submit 'Create'

app/views/questions/show.html.slim
.col-sm-6 style="max-width: 100%"
  strong Question
  .card
    .card-body
      strong Title
      h5= @question.title
      strong Body
      p= @question.body
      strong Attachments:
      ul
        - @question.attachments.each do |a|
          li= link_to a.file.identifier, a.file.url
        - if @question.attachments.empty?
          li Empty file list
        hr
        h4 Question Comments
        .question_comments
          - if !@question.comments.nil?
            - @question.comments.each do |comment|
              = render 'questions/comments', comment: comment, question: @question, user: current_user
          - else
            p There are no comments, be first who write smth
        -if current_user
          = form_for [@question, @question.comments.build], remote: true, data: { type: :json } do |f| #  html:{ id: @question_comment.id }
            = f.hidden_field :is_question?, value: true
            = f.label :body, "."
            = f.text_area :body
            = f.submit 'Create'
      .answers
        = render 'answers', question: @question, user: current_user

.col-sm-6 style="max-width: 100%"
  .card
    .card-body
      -if current_user
        strong Give answer
        = form_for [@question, @answer], remote: true, html: {id: @answer.id}, data: { type: :json } do |f|
          = f.label :body, 'Your answer'
          .answer-errors
          = f.text_area :body
          p Add Attachments:
          p
            = f.fields_for :attachments, @answer.attachments.build do |a|
              = render 'attachment_fields', f: a
          p
            = link_to_add_association "add file", f, :attachments
          = f.submit 'Create', class: 'button_create'

app/views/questions/subscribe.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.questions-errors').html('<%= j message %>')
  <% end %>
<% else %>
  console.log("SUBSCRIBE")
  $('.questions').html('<%= j render 'questions/questions', questions: Question.all %>');
<% end %>