config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  use_doorkeeper
  default_url_options host: 'localhost'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    confirmations: 'confirmations' }

  resource :search do
    post :result
    get :result
  end

  resources :questions do
    resources :answers do
      resources :comments
      post :position_edit, :cancel_choice
    end
    resources :comments
    post :subscribe, :cancel_subscrition
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :users, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  root to: 'questions#index'
  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qna2</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= action_cable_meta_tag %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/questions">Stackoverflow</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/questions">Questions <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to 'Exit', destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to 'Логін', new_user_session_path, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
    <% unless request.path.include? 'users/' %>
      <%= form_for :user, url: result_search_path, method: :post, html: { class: 'form-inline my-2 my-lg-0' } do |f| %>
        <strong>Include: </strong>
        <%= f.label "Questions" %> <br/>
        <%= f.check_box :Question %> <br/>
        <%= f.label "Answers" %> <br/>
        <%= f.check_box :Answer %> <br/>
        <%= f.label "Comments" %> <br/>
        <%= f.check_box :Comment %> <br/>
        <%= f.text_field :request, class: 'form-control mr-sm-2', label: false %>
        <%= f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0' %>
      <% end %>
    <% end %>
  </div>
</nav>

<div class="container">
  <div class="row">
    <% if user_signed_in? %>
      <p class="col-sm-6">You log in as: <%= current_user.email %></p>
    <% end %>
    <%= link_to 'Ask question', new_question_path, class: "col-sm-6" %>
  </div>
</div>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="row questions">
    <%= yield %>
  </div>
</div>
</body>
</html>